language: python
python:
  - "3.6"
install:
  # install latest release version
  - curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep "browser_download_url.*hugo_[^extended].*_Linux-64bit\.deb" | cut -d '"' -f 4 | wget -qi -
  - sudo dpkg -i hugo*.deb
  # - pip install Pygments
  - rm -rf public 2 > /dev/null
script:
    - hugo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  verbose: true
  keep-history: true
  on:
    branch: master